### ISSUE TITLE
failed to resolve v1.1 

### ISSUE THREAD

**Issue by android-guilherme** [Pierry/Progress#2]
In https://jitpack.io/#Pierry/Progress/1.1, the release says v1.0. 

In v1.0 shows me Manifest Merge error, pointing to icon ic_launcher...

**Comment by Pierry** [comment]
To solve:

Add in manifest

`
<manifest..
 xmlns:tools="http://schemas.android.com/tools"`

And in application:

`<application.. tools:node="replace"`
